name = "FeatureSetEnrichments"
uuid = "86280b8e-e847-4559-a126-2dcda5c07d84"
authors = ["Kevin Bonham", "PhD <kbonham@wellesley.edu> and contributors"]
version = "0.1.0"

[deps]
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"

[compat]
julia = "1.10"
