name = "FeatureSetEnrichments"
uuid = "86280b8e-e847-4559-a126-2dcda5c07d84"
authors = ["Kevin Bonham", "PhD <kbonham@wellesley.edu> and contributors"]
version = "0.2.0"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
# name of extension to the left
# extension dependencies required to load the extension to the right
# use a list for multiple extension dependencies
FSEAMakieExt = "Makie"

[compat]
julia = "1.10"

